TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray
Fixes an error with manager.py causing the following error.

 ~/stratasys $ ./stratasys-cartridge.py info --machine-type prodigy
--eeprom-uid d1000000a8ae2523 -i new_eeprom.bin
Traceback (most recent call last):
  File "./stratasys-cartridge.py", line 204, in <module>
    app.run()
  File "./stratasys-cartridge.py", line 47, in run
    args.func(args)
  File "./stratasys-cartridge.py", line 134, in command_info
    cartridge = m.decode(machine_number, args.eeprom_uid,
cartridge_crypted)
  File "/home/pi/stratasys/stratasys/manager.py", line 74, in decode
    cartridge = self.unpack(cartridge_packed)
  File "/home/pi/stratasys/stratasys/manager.py", line 137, in unpack
    serial_number = struct.unpack_from("<d", cartridge_packed, 0x0)[0]
TypeError: unpack_from() argument 1 must be string or read-only buffer,
not bytearray